<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Laboratory extends \App\Entity\Laboratory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'namelaboratory', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'codelaboratory', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'creePar', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'modifiePar', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'creeLe', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'modifieLe', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'products'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'namelaboratory', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'codelaboratory', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'creePar', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'modifiePar', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'creeLe', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'modifieLe', '' . "\0" . 'App\\Entity\\Laboratory' . "\0" . 'products'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Laboratory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNamelaboratory(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNamelaboratory', []);

        return parent::getNamelaboratory();
    }

    /**
     * {@inheritDoc}
     */
    public function setNamelaboratory(?string $namelaboratory): \App\Entity\Laboratory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNamelaboratory', [$namelaboratory]);

        return parent::setNamelaboratory($namelaboratory);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodelaboratory(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodelaboratory', []);

        return parent::getCodelaboratory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodelaboratory(?string $codelaboratory): \App\Entity\Laboratory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodelaboratory', [$codelaboratory]);

        return parent::setCodelaboratory($codelaboratory);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', []);

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduct(\App\Entity\Product $product): \App\Entity\Laboratory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduct', [$product]);

        return parent::addProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct(\App\Entity\Product $product): \App\Entity\Laboratory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct', [$product]);

        return parent::removeProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreePar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreePar', []);

        return parent::getCreePar();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreePar(?string $creePar): \App\Entity\Laboratory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreePar', [$creePar]);

        return parent::setCreePar($creePar);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiePar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiePar', []);

        return parent::getModifiePar();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiePar(?string $modifiePar): \App\Entity\Laboratory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiePar', [$modifiePar]);

        return parent::setModifiePar($modifiePar);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreeLe(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreeLe', []);

        return parent::getCreeLe();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreeLe(?\DateTimeInterface $creeLe): \App\Entity\Laboratory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreeLe', [$creeLe]);

        return parent::setCreeLe($creeLe);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifieLe(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifieLe', []);

        return parent::getModifieLe();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifieLe(?\DateTimeInterface $modifieLe): \App\Entity\Laboratory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifieLe', [$modifieLe]);

        return parent::setModifieLe($modifieLe);
    }

}
