<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXX9yx2X\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXX9yx2X/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXX9yx2X.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXX9yx2X\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXX9yx2X\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XX9yx2X',
    'container.build_id' => 'e0da0753',
    'container.build_time' => 1592565278,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXX9yx2X');
